# Generated by Django 3.1 on 2021-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cont',
            field=models.TextField(blank=True),
        ),
    ]
