# Generated by Django 3.1 on 2021-12-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_movie_cont'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.rating'),
        ),
    ]
