# Generated by Django 3.1 on 2021-12-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211219_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-time_created', 'title'], 'verbose_name': 'Mainp_movieslist'},
        ),
    ]
