# Generated by Django 3.1 on 2021-12-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211219_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(upload_to='img/%Y/%m/%d/'),
        ),
    ]
