# Generated by Django 3.1 on 2021-12-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211219_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cont',
            new_name='content',
        ),
    ]
